spring.application.name=tokenbucket
server.port=${PORT:8081}
spring.data.redis.host=redis-16142.c100.us-east-1-4.ec2.cloud.redislabs.com
spring.data.redis.port=16142
spring.data.redis.password=Mamoni@8228